### ISSUE TITLE
Change allow in robots.txt

### ISSUE THREAD

**Issue by lucasvazq** [lucasvazq/cushead#340]
## Description

Replace `/*` with `/` in Allow attr.

https://developers.google.com/search/docs/advanced/robots/create-robots-txt

**Comment by himanshu007-creator** [comment]
I would like to work on this issue.

**Comment by lucasvazq** [comment]
@himanshu007-creator 
Hello 👋👋👋!

I opened this issue thinking that I'm was creating robots.txt files using `Allow: /*`, but that's not true. I use `Allow: /` everywhere, so, nothing to do here.

Im going to close this issue, but there is another simple issue to do: https://github.com/lucasvazq/cushead/issues/339
