### ISSUE TITLE
ISSUE: Edit PR template

### ISSUE THREAD

**Issue by lucasvazq** [lucasvazq/cushead#66]
## Description
Add "# New features" to allow to user to specify new features that are included in the PR and are not specified in the issue or any other side

## Complements
[//]: # (Attach necessary files for the feature or provide code with titles separated in block)

**Comment by bsoyka** [comment]
Can I work on this?

**Comment by lucasvazq** [comment]
@bsoyka yeah bro!!

Add "# New Features" menu, or something like that to the pr templates.
Also, if you want, add AUTHORS to the repo, add me and add yourself

**Comment by bsoyka** [comment]
> @bsoyka yeah bro!!
> 
> Add "# New Features" menu, or something like that to the pr templates.

Will do. :)
___
> ~Also, if you want, add AUTHORS to the repo, add me and add yourself~
> When you contribute all can see you in https://github.com/lucasvazq/cushead/graphs/contributors or doing `git shortlog -s | cut -c8-` under the repository root folder

:+1:

**Comment by bsoyka** [comment]
@lucasvazq, do you mind if I try to clean up the PR template a little bit as well?

**Comment by lucasvazq** [comment]
@bsoyka feel free, no problem!
