### ISSUE TITLE
ISSUE: EDIT CONTRIBUTING

### ISSUE THREAD

**Issue by lucasvazq** [lucasvazq/cushead#67]
## Description
Whe user adds new features in PR, need to create an issue related to those new features, mention that Issue in the PR and close it.
For the issue, need to specify projects, milestone, epics or releases (if have).
The estimate would be passed.
Also, need to add the correspondent labels

If the PR is ready to merge, the issue don't need to work on. So, they don't need any label, the same for milestones, etc

## Complements
[//]: # (Attach necessary files for the feature or provide code with titles separated in block)

**Comment by lucasvazq** [comment]
UPDATE:
For PR without issue need to create an issue related that PR solves

**Comment by bsoyka** [comment]
If a user is not a contributor on the repo, they can’t add labels, milestones, etc. as far as I know.

**Comment by lucasvazq** [comment]
@bsoyka I think I need to dedicate more time to learn about git then.. :thinking:
